### ISSUE TITLE
JOSS Review

### ISSUE THREAD

**Issue by nistara** [meenakshi-kushwaha/mmaqshiny#3]
Hi, thank you for submitting your package to JOSS and inviting me to review it. It's an interesting and useful package and I've definitely learnt more about air pollution measurements from it! Below are my comments:

1. You have two license files, one with the MIT license which matches the journal guidelines, and another with just your names and year. I believe you should have just one valid license file. Same for the package description: it says MIT + file LICENSE.

2. I suggest moving the image files from your main package folder to the inst folder or another relevant one to clean up your package structure.

3. In your manuscript, improve the specific details para (para 3), especially towards the end. It is one big long line with an error as well. Additionally, you use carbon-di-oxide for carbon dioxide. Is that the accepted nomenclature?

    "Specific details of instruments and parameters measured can be found in the “Instrument Details” section. Briefly, high frequency (1 Hz) data of  PM2.5 (mass concentrations of particulate matter with size less than 2.5 microns); black carbon mass concentrations (BC); ultra-fine particle number concentrations; carbon-di-oxide (CO2); GPS coordinates and relative humidity (RH) data are collected by some popular portable instruments (TSI DustTrak-8530, Aethlabs microAeth-AE51, TSI CPC3007, LICOR Li-850, Garmin GPSMAP 64s and Omega USB RH probe, respectively), can be handled by this package."

    In the above para's "data are collected by some popular portable instruments" line, it will make more sense to remove the "are" to make the entire line coherent. Unless, of course, you decide to split the line up.

4. In paragraph 4, "Under the hood, this app performs two basic functions -", it is recommended to use ":" instead of "-".

    - In the same para (4), 
    "As mentioned before, air-pollution measurements, especially BC from microAeth, on a mobile platform is susceptible to vibration-related noise because of the road conditions and vehicle suspension efficiency" 
    it should be 
    "As mentioned before, air-pollution measurements, especially BC from microAeth, on a mobile platform **are** susceptible to vibration-related noise because of the road conditions and vehicle suspension efficiency"

    - Again in para 4, "following Apte et al. (2011) method" should be "following **the** Apte et al. (2011) method". And "To correct for RH, an algorithm is applied to DustTrak  PM.5 following **the** Chakrabarti method." Either add "the" in front of the method names, or write "using the method by so and so".

5. In some places you use "air pollution", whereas at least twice you use "air-pollution". Usage should be consistent, and I believe "air pollution" is the way to go, though I leave it to your discretion and experience to choose either.

6. In App Display section point 4, generally the term "basemap" is used instead of "background".

7. In the App Display section, each sentence begins with a capital letter, whereas the Limitations sections has all lowercase words. Use the same style for both sections. Similarly, point 4 of App Display is punctuated with a period, while none of the other lines are. Choose one or the other and apply to all. 

8. The R code for the app in `inst/shiny/app.R` has style issues that can be improved:
     - Sometimes `=` is used for assignment and in other places `<-` is used (recommend choosing one style and sticking with it). For e.g.
```
df_list <- lapply(inFile$datapath, function(y){

# vs

files3 = lapply(inFile$datapath, function(y){

# and

JSON_csv =read.delim(y, header=TRUE, sep=";", row.names=NULL, skip=2)
JSON_csv_date<-as.character(JSON_csv[1,1])
```
      
  - As seen above, regardless of assignment operator used, spacing in code is inconsistent.
  - Finally, the code lines stretch very long, beyond the recommended 80 characters (or around it, depending on your preference). 
  - For helpful references on the above, see  http://adv-r.had.co.nz/Style.html and https://devguide.ropensci.org/building.html#code-style

9. Any reason why MtbMap was used as a basemap? It shows mountain bike, cycling and hiking tracks in Europe (https://wiki.openstreetmap.org/wiki/MTB_map_Europe). If your app is expected to be used worldwide, I'm not sure why you'd have a Europe-specific basemap. The relevant code in your app is:

```
leaflet(data) %>% addProviderTiles(providers$MtbMap) %>%
      addProviderTiles(providers$Stamen.TonerLines,
                       options = providerTileOptions(opacity = 0.25))
```

  When zooming out on the map display, the MtbMap basemap stands out like below:
<img width="1192" alt="Screen Shot 2020-06-15 at 11 24 12 PM" src="https://user-images.githubusercontent.com/12116051/84838693-e7400b00-afef-11ea-88e3-c1f3ef3547df.png">

   You can see how your basemaps will appear from this really useful site: http://leaflet-extras.github.io/leaflet-providers/preview/index.html

10. In addition, for some of the pollutants (notably BC), I get the following error when I look at the map: 
`Warning:  1 failed to parse.
Warning in pal(data[[input$palleInp]]) :
  Some values were outside the color scale and will be treated as NA`
    I'm not entirely sure why the above warning came up, but upon closer look, it seems that the minimum values for BC are in the negatives, while the map legend starts with 0 as the minimum value. I'm not as conversant with what the normal pollutant range can be, but I think you might want to explain why this is or whether you have a reason for excluding the negative values (and edit the code so that this warning either doesn't occur, or is more informative). Please let me know if you don't come across this warning - it could be that some of my local packages (dependencies) aren't completely updated and the newer versions plot without the warning. Regardless, future users might get the same warnings. 

11. Upon running devtools:check() I came across these warnings:
    - `❯ checking for portable file names ... WARNING
Found the following file with a non-portable file name:
    inst/shiny/data/GPSMAP 64s
  These are not fully portable file names.
  See section ‘Package structure’ in the ‘Writing R Extensions’ manual.`
    - `❯ checking DESCRIPTION meta-information ... WARNING
  Dependence on R version ‘3.5.1’ not with patchlevel 0`
    See https://stackoverflow.com/q/48433412 for more information on the second warning. I recommend implementing the fixes, but leave it to your discretion.

12.  Finally, you incorporated @ibarraespinosa's suggestions in your code, but didn't update your tests (especially relevant for the timezone edit). Using `shinytest::testApp("inst/shiny/")` helped me see how the original output you recorded differed from the current one with the updates. I recommend updating your tests if you're going to make important updates to your code. I also agree with his comment on having too many dependencies!

Please let me know if you have any questions.
Thank you and all the best!

**Comment by adithirgis** [comment]
Thank you so much @nistara. Here are our responses:

1. As per our understanding,  MIT License should be accompanied by a file license for completeness.  This is also mentioned in  https://www.r-project.org/Licenses/MIT and https://r-pkgs.org/description.html#license. We are happy to incorporate your suggestions further, if any.
2. As per suggestion, we have moved the images to the ‘inst/images’ folder.
3. As suggested, the paragraph was split into two and the other minor comments were taken care of.
4. Revised as per suggestion.
5. Revised as per suggestion. 
6. Revised as per suggestion. 
7. Revised as per suggestion. 
8. Thank you for the informative resource. Suggestions were taken care of in the revised code.
9. As per suggestion, we have replaced the MtbMap tile with Stamen.TonerLite for it to be useful worldwide. Again, thank you for the resource.
10. Yes, the uncorrected (raw) BC values can be negative owing to the instrument's sensitivity to vibration. We have adjusted the colour ramp to display negative values as well.
11. We have renamed the concerned folder and changed the version.
12. We have updated the tests folder after various smaller tests. We have converted the timezone from a text input to a dropdown menu using this function: OlsonNames() to avoid errors in the timezones. After the changes to the app we have performed the tests. 
Since there were too many packages imported we have now reduced the **_Imports_** from over 30 to below 20 and added some to **_Suggests_**.

**Comment by nistara** [comment]
Hi @adithirgis, I see you've implemented the suggestions, as well as made further updates yourself. 

Thank you for pointing out the resources for the MIT license. The previous JOSS publication I looked up as a reference did not have two license files, and that seems to be the case for the majority of them, although a few do have two. Adding some (including R packages submitted to CRAN) below for your reference: 
- https://github.com/PsyChiLin/EFAshiny
- https://github.com/michaellevy/gwdegree
- https://github.com/cran/plotly
- https://github.com/cran/politicaldata
- https://github.com/r-lib/testthat
- https://github.com/samhforbes/PupillometryR
- https://github.com/ropensci/spelling
- https://github.com/jeroen/jsonlite
- https://github.com/ycphs/openxlsx

Hopefully the above should be helpful if you decide to submit to CRAN later. There seem to be a few iterations of how to describe the license.

I'm going to wrap up my review now!
Best wishes and stay safe,
Nistara

**Comment by adithirgis** [comment]
Thank you for the resources, we are planning to submitting it to CRAN as well. This would be helpful. 
Also, should I close this issue now? 

Thank you so much again @nistara. 
 Stay safe!

**Comment by nistara** [comment]
Just closed it :) 
You're most welcome and wish you the best with this going forward!
